import Head from 'next/head';
import styled from 'styled-components';
import Footer from '../footer';

// Types
interface LayoutProps {
  children: React.ReactNode;
}

// Styles
const MainStyled = styled.main`
  margin: 0 auto;
  width: 100%;
  max-width: 1440px;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon-32x32.png" />
      </Head>
      <MainStyled>{children}</MainStyled>
      <Footer />
    </>
  );
}
